/**
 * Canonical service vendor specialties (`service_categories.slug`).
 * Master doc: docs/service-categories-taxonomy.md
 * Hub groups: lib/service-categories/groups.ts
 */
export const SERVICE_CATEGORY_SLUGS = [
  // outdoor_property
  "landscaping",
  "lawn_care",
  "pool_spa",
  "irrigation",
  "pest_control",
  "property_management",
  "vacation_rentals",
  "home_staging",
  // home_trades
  "plumbing",
  "electrical",
  "hvac",
  "painting",
  "handyman",
  "roofing",
  "cleaning",
  "pressure_washing",
  "junk_removal",
  "moving",
  "flooring",
  "concrete_masonry",
  "home_exterior",
  "appliance_repair",
  "solar_energy",
  "restoration",
  "contractors",
  "home_improvement",
  "home_inspection",
  "security_systems",
  // marine
  "marine_boat",
  // professional
  "insurance",
  "accounting",
  "legal",
  "real_estate",
  "financial",
  "staffing",
  "engineering_survey",
  // health_wellness
  "health_medical",
  "counseling",
  "veterinary",
  "salon_spa",
  "fitness_wellness",
  // creative_events
  "design_architecture",
  "photography",
  "events_wedding",
  "catering_events",
  "marketing_creative",
  // tech_office
  "it_computer",
  "office_workspace",
  // auto_transport
  "auto_repair",
  "towing_transport",
  "car_rental",
  // family_pets
  "education_childcare",
  "pet_services",
  // other_services
  "storage",
  "waste_septic",
  "laundry_dry_clean",
] as const;

export type ServiceCategorySlug = (typeof SERVICE_CATEGORY_SLUGS)[number];

export const SERVICE_CATEGORY_LABELS: Record<ServiceCategorySlug, string> = {
  landscaping: "Landscaping",
  lawn_care: "Lawn care",
  pool_spa: "Pool & spa",
  irrigation: "Irrigation",
  pest_control: "Pest control",
  property_management: "Property management",
  vacation_rentals: "Vacation rentals",
  home_staging: "Home staging",
  plumbing: "Plumbing",
  electrical: "Electrical",
  hvac: "HVAC",
  painting: "Painting",
  handyman: "Handyman",
  roofing: "Roofing",
  cleaning: "Cleaning",
  pressure_washing: "Pressure washing",
  junk_removal: "Junk removal",
  moving: "Moving & hauling",
  flooring: "Flooring",
  concrete_masonry: "Concrete & masonry",
  home_exterior: "Exterior & openings",
  appliance_repair: "Appliance repair",
  solar_energy: "Solar & energy",
  restoration: "Restoration",
  contractors: "Contractors",
  home_improvement: "Home improvement",
  home_inspection: "Home inspection",
  security_systems: "Security systems",
  marine_boat: "Marine & boat",
  insurance: "Insurance",
  accounting: "Accounting & tax",
  legal: "Legal",
  real_estate: "Real estate & title",
  financial: "Financial advisory",
  staffing: "Staffing & recruiting",
  engineering_survey: "Engineering & survey",
  health_medical: "Health & medical",
  counseling: "Counseling",
  veterinary: "Veterinary",
  salon_spa: "Salon & spa",
  fitness_wellness: "Fitness & wellness",
  design_architecture: "Design & architecture",
  photography: "Photography",
  events_wedding: "Events & weddings",
  catering_events: "Event catering",
  marketing_creative: "Marketing & creative",
  it_computer: "IT & computers",
  office_workspace: "Office & workspace",
  auto_repair: "Auto repair",
  towing_transport: "Towing & transport",
  car_rental: "Car rental",
  education_childcare: "Education & childcare",
  pet_services: "Pet services",
  storage: "Storage",
  waste_septic: "Waste & septic",
  laundry_dry_clean: "Laundry & dry clean",
};

/** OpenAI classify script — one line per slug. */
export const SERVICE_CATEGORY_CLASSIFICATION_GUIDE: Record<ServiceCategorySlug, string> = {
  landscaping: "Landscape design, planting, commercial/residential landscape companies",
  lawn_care: "Mowing, fertilizing, turf-only maintenance",
  pool_spa: "Pool/spa cleaning, repair, service",
  irrigation: "Sprinkler and irrigation install/repair",
  pest_control: "Exterminators, termite, pest prevention",
  property_management: "Long-term rental, HOA, building management",
  vacation_rentals: "Vacation/STR rental managers and agencies",
  home_staging: "Home staging for sale or rental",
  plumbing: "Plumbers, drains, water heaters",
  electrical: "Electricians, panels, lighting",
  hvac: "Heating, cooling, mechanical contractors",
  painting: "Residential/commercial painters",
  handyman: "Handyman and small repairs",
  roofing: "Roofing contractors",
  cleaning: "House cleaning, maid, janitorial",
  pressure_washing: "Pressure/soft wash exteriors",
  junk_removal: "Junk haul-away, debris removal (not full moving company)",
  moving: "Movers and large hauling",
  flooring: "Flooring, tile, epoxy, carpet installers",
  concrete_masonry: "Concrete, masonry, retaining walls",
  home_exterior: "Windows, doors, gutters, fencing installers",
  appliance_repair: "Appliance repair service",
  solar_energy: "Solar panels, generators, energy install",
  restoration: "Fire, water, mold restoration",
  contractors: "General contractors, remodelers",
  home_improvement: "Cabinets, closets, counters, blinds, interior suppliers",
  home_inspection: "Home and pre-listing inspectors",
  security_systems: "Alarms, cameras, monitoring",
  marine_boat: "Boat yards, marine repair, charters, watersports rentals",
  insurance: "Insurance agencies",
  accounting: "CPA, tax, bookkeeping, payroll",
  legal: "Law firms and attorneys",
  real_estate: "Realtors, title, escrow",
  financial: "Wealth management and financial advisors",
  staffing: "Staffing and recruiting agencies",
  engineering_survey: "Engineering, civil, surveying, A&E firms",
  health_medical: "Medical, dental, derm, clinics, rehab, hospice practices",
  counseling: "Therapy and mental health practices",
  veterinary: "Veterinary clinics",
  salon_spa: "Hair, nails, day spa, med spa",
  fitness_wellness: "Pilates, yoga, gyms, personal training studios",
  design_architecture: "Interior designers and architects",
  photography: "Photographers and photo studios",
  events_wedding: "Wedding/event planners, florists, DJs",
  catering_events: "Catering companies (event, not sit-down restaurant)",
  marketing_creative: "Marketing, ad agencies, signage/print shops",
  it_computer: "IT support, MSP, computer repair, web development",
  office_workspace: "Coworking and flex office",
  auto_repair: "Auto mechanics and body shops",
  towing_transport: "Towing, limo, private car service",
  car_rental: "Car rental agencies",
  education_childcare: "Daycare, tutoring, music/lessons",
  pet_services: "Pet grooming, boarding, training",
  storage: "Self-storage facilities",
  waste_septic: "Septic, dumpsters, portable toilets",
  laundry_dry_clean: "Dry cleaning and laundromats",
};

export const SERVICE_CATEGORY_ICONS: Record<string, string> = {
  landscaping: "yard",
  lawn_care: "grass",
  pool_spa: "pool",
  irrigation: "water",
  pest_control: "pest_control",
  property_management: "apartment",
  vacation_rentals: "holiday_village",
  home_staging: "chair",
  plumbing: "plumbing",
  electrical: "bolt",
  hvac: "ac_unit",
  painting: "format_paint",
  handyman: "handyman",
  roofing: "roofing",
  cleaning: "cleaning_services",
  pressure_washing: "water_drop",
  junk_removal: "delete_sweep",
  moving: "local_shipping",
  flooring: "layers",
  concrete_masonry: "foundation",
  home_exterior: "door_front",
  appliance_repair: "kitchen",
  solar_energy: "solar_power",
  restoration: "home_repair_service",
  contractors: "construction",
  home_improvement: "countertops",
  home_inspection: "fact_check",
  security_systems: "shield",
  marine_boat: "sailing",
  insurance: "verified_user",
  accounting: "calculate",
  legal: "gavel",
  real_estate: "real_estate_agent",
  financial: "account_balance",
  staffing: "groups",
  engineering_survey: "architecture",
  health_medical: "medical_services",
  counseling: "psychology",
  veterinary: "pets",
  salon_spa: "spa",
  fitness_wellness: "fitness_center",
  design_architecture: "design_services",
  photography: "photo_camera",
  events_wedding: "celebration",
  catering_events: "restaurant_menu",
  marketing_creative: "campaign",
  it_computer: "computer",
  office_workspace: "work",
  auto_repair: "car_repair",
  towing_transport: "local_taxi",
  car_rental: "car_rental",
  education_childcare: "school",
  pet_services: "pets",
  storage: "warehouse",
  waste_septic: "delete",
  laundry_dry_clean: "local_laundry_service",
};
