import { SERVICE_CATEGORY_SLUGS } from "@/lib/service-categories/constants";

const ALIASES: Record<string, (typeof SERVICE_CATEGORY_SLUGS)[number]> = {
  lawn: "lawn_care",
  "lawn-care": "lawn_care",
  pool: "pool_spa",
  "pool-spa": "pool_spa",
  "pressure-washing": "pressure_washing",
  pest: "pest_control",
  "pest-control": "pest_control",
  boat: "marine_boat",
  marine: "marine_boat",
  watersports: "marine_boat",
  hauling: "moving",
  property: "property_management",
  title: "real_estate",
  state_farm: "insurance",
  insurance_agency: "insurance",
  insurer: "insurance",
  escrow: "real_estate",
  realtor: "real_estate",
  cpa: "accounting",
  tax: "accounting",
  attorney: "legal",
  attorneys: "legal",
  lawyer: "legal",
  law: "legal",
  law_firm: "legal",
  legal_services: "legal",
  dentist: "health_medical",
  dental: "health_medical",
  medical: "health_medical",
  dermatology: "health_medical",
  hospice: "health_medical",
  healthcare: "health_medical",
  home_health: "health_medical",
  therapy: "counseling",
  cabinets: "home_improvement",
  closets: "home_improvement",
  blinds: "home_improvement",
  coworking: "office_workspace",
  flexspace: "office_workspace",
  junk: "junk_removal",
  staging: "home_staging",
  str: "vacation_rentals",
  vet: "veterinary",
  salon: "salon_spa",
  spa: "salon_spa",
  fitness: "fitness_wellness",
  photo: "photography",
  wedding: "events_wedding",
  catering: "catering_events",
  marketing: "marketing_creative",
  it: "it_computer",
  mechanic: "auto_repair",
  limo: "towing_transport",
  daycare: "education_childcare",
  tutoring: "education_childcare",
  septic: "waste_septic",
  dumpster: "waste_septic",
  laundry: "laundry_dry_clean",
  engineer: "engineering_survey",
  survey: "engineering_survey",
  gutter: "home_exterior",
  fence: "home_exterior",
  window: "home_exterior",
};

export function normalizeServiceCategorySlug(
  slug: string | null | undefined,
): string | null {
  if (!slug?.trim()) return null;
  const key = slug.trim().toLowerCase().replace(/\s+/g, "_").replace(/-/g, "_");
  const aliased = ALIASES[key];
  if (aliased) return aliased;
  if ((SERVICE_CATEGORY_SLUGS as readonly string[]).includes(key)) return key;
  return null;
}
