/**
 * Canonical tag + business_type vocabulary for storefront/service listings.
 *
 * Source of truth for `scripts/normalize-business-tags.ts` and for the
 * `search_tags_vocabulary` seed migration. See `docs/search-tags-taxonomy.md`
 * for the human-readable reference built from this file.
 *
 * Built by hand from a frequency analysis of `docs/storefronts-audit.csv`
 * (444 rows) and `docs/services-audit.csv` (122 rows) — no LLM involved.
 */

export function normalizeSlug(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // strip combining accents: e.g. e-acute->e, n-tilde->n
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/** Canonical tag vocabulary, grouped for docs/migration generation. Union = CANONICAL_TAGS. */
export const TAG_GROUPS: Record<string, string[]> = {
  vibe_occasion: [
    "casual", "family_outing", "locals_favorite", "lively", "family_friendly",
    "quick_bite", "colorful", "souvenir_shopping", "tourist_attraction", "girls_trip",
    "cozy", "trendy", "date_night", "upscale", "special_occasion", "welcoming",
    "celebration", "dining", "gift_shopping", "friendly", "beachfront", "waterfront",
    "intimate", "kid_friendly", "romantic", "relaxed", "self_care", "stylish",
    "modern", "dog_friendly", "pet_friendly", "fine_dining", "casual_dining",
    "rainy_day", "vibrant", "airy", "charming", "elegant", "quiet", "serene",
    "chic", "eclectic", "wellness", "solo", "warm", "inviting", "quirky",
    "sophisticated", "historic", "scenic", "outdoor_seating", "live_music",
    "personalized", "supportive", "caring", "compassionate", "convenient",
    "affordable", "local",
  ],
  dietary_meal_period: [
    "vegan", "vegetarian", "gluten_free", "dairy_free",
    "breakfast", "brunch", "lunch", "dinner", "late_night",
  ],
  food_drink: [
    "seafood", "steak", "sushi", "pizza", "bbq", "burgers", "tacos", "mexican",
    "italian", "asian", "mediterranean", "southern", "cajun", "pasta",
    "sandwiches", "salads", "wings", "hot_dogs", "dumplings", "crepes",
    "pastries", "bakery", "donuts", "candy", "chocolate", "desserts", "ice_cream",
    "gelato", "acai_bowls", "coffee", "tea", "espresso", "smoothies", "juice",
    "wine", "beer", "cocktails", "casual_drinks", "non_alcoholic_drinks",
  ],
  retail: [
    "apparel", "kids_apparel", "swimwear", "beachwear", "footwear", "accessories",
    "jewelry", "hats", "home_decor", "gifts", "specialty_gifts", "souvenirs",
    "books", "art", "toys", "collectibles", "candles", "beauty_products",
    "pet_accessories", "plants", "sporting_goods",
  ],
  activity_rental: ["bike_rentals", "water_sports_rentals", "mobility_rental", "golf"],
  health_beauty: [
    "salon_services", "nail_services", "spa_services", "massage", "skincare",
    "dental_care", "dermatology", "chiropractic_care", "counseling",
    "medical_care", "healthcare", "hospice_rehab_care", "veterinary_care",
    "fitness_classes", "yoga",
  ],
  home_trades_professional: [
    "hvac_repair", "plumbing", "electrical", "roofing", "pest_control",
    "landscaping", "lawn_care", "cleaning_services", "handyman",
    "home_improvement", "window_treatments", "cabinetry", "flooring",
    "painting", "home_inspection", "security_systems", "restoration",
    "contractors", "insurance", "accounting", "tax_prep", "bookkeeping",
    "financial_planning", "legal_services", "real_estate", "title_escrow",
    "property_management", "photography", "coworking", "transportation",
    "travel_services", "printing_shipping", "banking",
    "entertainment_screenings", "sustainable", "activities",
  ],
};

export const CANONICAL_TAGS: string[] = Object.values(TAG_GROUPS).flat();

export const CANONICAL_TAG_SET = new Set(CANONICAL_TAGS);

/** Exact-match synonym map (key = normalizeSlug(raw tag)). Applied before keyword rules. */
export const TAG_SYNONYMS: Record<string, string> = {
  // vibe / adjectives
  classy: "upscale", refined: "upscale", polished: "upscale", premium: "upscale",
  luxurious: "upscale", elevated: "upscale", sophisticated: "upscale",
  quaint: "charming", rustic: "cozy", homey: "cozy", intimate_setting: "intimate",
  bustling: "lively", energetic: "lively", dynamic: "lively", vibrant_atmosphere: "lively",
  calm: "quiet", tranquil: "quiet", peaceful: "quiet", relaxing: "relaxed",
  laid_back: "relaxed", laidback: "relaxed", unpretentious: "casual",
  artsy: "eclectic", whimsical: "eclectic", nostalgic: "charming",
  tasteful: "stylish", classic: "trendy",
  creative: "eclectic", artistic: "art", bright: "colorful", comfortable: "cozy",
  pleasant: "welcoming", accommodating: "welcoming", spacious: "airy",
  friendly_staff: "friendly", friendly_service: "friendly",
  functional: "convenient",
  local_favorite: "locals_favorite",
  tourist_favorite: "tourist_attraction", touristy: "tourist_attraction",
  family_activity: "family_outing", family_dining: "family_friendly",
  family_vacation: "family_outing", kid_friendly_bike_rentals: "bike_rentals",
  kid_friendly_dining: "kid_friendly", birthday: "celebration",
  birthday_parties: "celebration", special_event: "special_occasion",
  wedding: "special_occasion", weddings: "special_occasion",
  romantic_getaway: "romantic", business_travel: "travel_services",
  business_trip: "travel_services", solo_traveler: "solo",
  community: "locals_favorite", community_feel: "locals_favorite",
  community_hub: "locals_favorite", community_atmosphere: "locals_favorite",
  community_events: "locals_favorite", welcoming_atmosphere: "welcoming",
  eco_friendly: "sustainable", sustainable: "sustainable",
  sweets: "desserts", dessert: "desserts", desserts: "desserts",
  classic_flavors: "desserts", beignets: "pastries",
  takeout: "quick_bite", takeout_boxes: "quick_bite",
  vegetarian_options: "vegetarian", waterfront_dining: "waterfront",
  adventure: "activities", deli: "sandwiches",
  dinner_with_friends: "date_night", personalized_service: "personalized",
  lunch_options: "lunch", beach_outing: "family_outing",
  henna: "beauty_products", morning_treat: "breakfast",
  leisurely_morning: "breakfast",

  // food/drink
  seafood_focused_entrees: "seafood", local_seafood: "seafood", oysters: "seafood",
  oyster_bar: "seafood", scallops: "seafood", shrimp: "seafood", snapper: "seafood",
  panko_red_snapper: "seafood", grilled_fish: "seafood", clam_chowder: "seafood",
  lobster_roll: "seafood", lobster_dishes: "seafood", seafood_ceviche: "seafood",
  seafood_platter: "seafood", crab_cakes: "seafood", crab_cake_benedict: "seafood",
  shrimp_and_crab_dip: "seafood", shrimp_grits: "seafood", shrimp_tacos: "tacos",
  fish_tacos: "tacos", nachos: "mexican", brisket_nachos: "bbq", enchiladas: "mexican",
  fajitas: "mexican", coastal_mexican_fare: "mexican", mexican_cuisine: "mexican",
  taqueria: "mexican", breakfast_tacos: "tacos", chips_and_salsa: "mexican",
  tomahawk_pork_chop: "steak", ny_strip_steak: "steak", steak_options: "steak",
  steakhouse: "steak", ribeye: "steak", filet: "steak",
  fresh_sushi: "sushi", sushi_rolls: "sushi", tuna_rolls: "sushi", florida_roll: "sushi",
  sushi_bar: "sushi", tuna_tartare: "seafood", modern_japanese: "asian",
  pan_asian_cuisine: "asian", mongolian_beef: "asian", tofu_peanut_rice_noodle: "asian",
  upscale_asian_restaurant: "asian", thai: "asian", pepperoni_pizza: "pizza",
  cheese_pizza: "pizza", margarita_pizza: "pizza", bbq_chicken_pizza: "pizza",
  aloha_pizza: "pizza", farmers_market_pizza: "pizza", billy_goat_pizza: "pizza",
  gluten_free_pizza: "pizza", cracker_thin_crust: "pizza", pizzeria: "pizza",
  hot_honey_pepperoni: "pizza", barbecue: "bbq", brisket: "bbq", bbq_sauce: "bbq",
  smash_burgers: "burgers", burger_restaurant: "burgers", burritos: "mexican",
  breakfast_burrito: "breakfast", breakfast_burritos: "breakfast", cheesesteaks: "sandwiches",
  fried_chicken_sandwich: "sandwiches", chicken_sandwich: "sandwiches",
  buffalo_chicken_wrap: "sandwiches", chicken_spinach_wrap: "sandwiches", wraps: "sandwiches",
  subs: "sandwiches", sub_sandwich_shop: "sandwiches", cubano_sandwiches: "sandwiches",
  deli_sub: "sandwiches", grilled_cheese: "sandwiches", grilled_cheese_restaurant: "sandwiches",
  inside_out_brisket_grilled_cheese_buns: "sandwiches", monte_cristo: "sandwiches",
  gyros: "mediterranean", gyro_with_fries_combo: "mediterranean",
  lamb_and_beef_mixed_gyro: "mediterranean", greek_restaurant: "mediterranean",
  italian_cuisine: "italian", italian_restaurant: "italian", lasagna: "italian",
  fettuccine_alfredo: "italian", homemade_pasta: "pasta", spaghetti_and_meatballs: "pasta",
  dumplings: "dumplings", chicken_fried_rice: "asian", pork_buns: "dumplings",
  boba_and_boozy_drinks: "asian", savory_crepes: "crepes", sweet_crepes: "crepes",
  crepe_restaurant: "crepes", crepery: "crepes", salads: "salads", chicken_salad: "salads",
  seaweed_salad: "salads", southwest_salad_bowl: "salads", potato_salad: "salads",
  adobo_chicken_wings: "wings", hot_dogs: "hot_dogs", hot_dog_restaurant: "hot_dogs",
  cajun: "cajun", gumbo: "cajun", southern: "southern", southern_classics: "southern",
  southern_benedict: "southern", southern_coastal_restaurant: "southern",
  coastal_grill: "seafood", creative_coastal_fare: "seafood",
  globally_inspired_dishes: "asian", pastries: "pastries", breakfast_pastries: "pastries",
  gluten_free_treats: "pastries", croissant: "pastries", biscuits_and_gravy: "pastries",
  biscuit_breakfast: "pastries", fluffy_biscuits: "pastries", cinnamon_rolls: "pastries",
  churro_waffles: "pastries", waffles: "pastries", waffle_cones: "pastries",
  fresh_waffle_cones: "ice_cream", pancakes: "pastries",
  classic_gluten_free_pancakes: "pastries", gluten_free_pancakes: "pastries",
  lemon_blueberry_goat_cheese_pancakes: "pastries", eggs_benedict: "pastries",
  omelets: "pastries", creole_omelet: "pastries", huevos_rancheros: "pastries",
  hearty_breakfast: "breakfast", quiche_with_applewood_smoked_bacon: "pastries",
  bread: "bakery", rosemary_bread: "bakery", mozzarella_bread: "bakery",
  stuffed_crawfish_bread: "bakery", bakery_items: "bakery", cookies: "bakery",
  freshly_baked_cookies: "bakery", custom_cookie_cakes: "bakery",
  organic_baked_goods: "bakery", brownies: "bakery", donuts: "donuts",
  doughnuts: "donuts", handmade_donuts: "donuts", classic_glazed: "donuts",
  cinnamon_sugar_twist: "donuts", donut_shop: "donuts", candy_sticks: "candy",
  bulk_candy: "candy", hard_candies: "candy", sour_candies: "candy",
  gummy_bears: "candy", gummies: "candy", nostalgic_candy: "candy",
  colorful_lollipops: "candy", oversized_lollipops: "candy", pickle_cotton_candy: "candy",
  prepackaged_candy: "candy", candy_by_the_pound: "candy", candy_store: "candy",
  chocolate_bars: "chocolate", chocolates: "chocolate", chocolate_ganache: "chocolate",
  chocolate_dipped_bananas: "chocolate", peanut_butter_fudge: "chocolate", fudge: "chocolate",
  brittles: "candy", pralines: "candy", bourbon_pecan_praline: "candy",
  ice_cream: "ice_cream", homemade_ice_cream: "ice_cream", hand_blended_ice_cream: "ice_cream",
  various_ice_cream_flavors: "ice_cream", mint_chocolate_chip: "ice_cream",
  raspberry_ice_cream: "ice_cream", banana_pudding_ice_cream: "ice_cream",
  butterfinger_ice_cream: "ice_cream", dark_chocolate_frozen_yogurt: "ice_cream",
  salted_caramel_yogurt: "ice_cream", sherbet: "ice_cream", shaved_ice: "ice_cream",
  snow_cone: "ice_cream", frozen_treats: "ice_cream", coconut_gelato: "gelato",
  acai_bowls: "acai_bowls", pitaya_bowls: "acai_bowls", fresh_bowls: "acai_bowls",
  acai_bowl_restaurant: "acai_bowls", coffee_shop: "coffee",
  coffee_bar: "coffee", coffee_options: "coffee", specialty_coffees: "coffee",
  locally_roasted_coffee: "coffee", locally_roasted_coffee_beans: "coffee",
  lucky_goat_coffee: "coffee", hot_brews: "coffee", drip_coffee: "coffee",
  cold_brew: "coffee", cortado: "coffee", flat_white: "coffee", iced_coffee: "coffee",
  iced_oat_milk_latte: "coffee", pumpkin_spice_latte: "coffee", lattes: "coffee",
  espresso: "espresso", vietnamese_cold_brew: "coffee", lotus_tea: "tea",
  smoothie_bowl_restaurant: "smoothies", milkshakes: "smoothies", shakes: "smoothies",
  wine_selection: "wine", beer_wine: "wine", craft_beer: "beer", craft_beers: "beer",
  local_brews: "beer", craft_beverages: "cocktails", cocktail_items: "cocktails",
  cocktail_lounge: "cocktails", classic_cocktails: "cocktails",
  creative_cocktails: "cocktails", signature_cocktails: "cocktails",
  frozen_cocktails: "cocktails", frozen_drinks: "cocktails", frozen_drink_bar: "cocktails",
  sunset_cocktails: "cocktails", margaritas: "cocktails", pina_colada: "cocktails",
  whiskey_mule: "cocktails", lychee_martini: "cocktails", deadwood_sweet_jane: "cocktails",
  cucumber_mint: "cocktails", luna_rosa: "cocktails", tropical_drinks: "cocktails",
  bar_drinks: "cocktails", ghost_in_the_machine_double_hazy_ipa: "beer",
  non_alcoholic_beverages: "non_alcoholic_drinks", fresh_lemonade: "non_alcoholic_drinks",
  organic_juices: "juice", pineapple_cider: "cocktails",
  american_bar_fare: "casual_drinks", bar_food: "casual_drinks", bar: "casual_drinks",

  // retail
  home_goods: "home_decor", home_decor_art: "home_decor", home_decor: "home_decor",
  home_furnishings: "home_decor", designer_homeware: "home_decor",
  outdoor_decor: "home_decor", functional_decor: "home_decor", decor_items: "home_decor",
  decorative_items: "home_decor", stylish_decor: "home_decor",
  unique_home_furnishings: "home_decor", home_interiors_shop: "home_decor",
  home_furnishings_showroom: "home_decor", furnishings: "home_decor",
  furniture: "home_decor", furniture_store: "home_decor", bedroom_sets: "home_decor",
  small_kitchen_goods: "home_decor", home_accessories: "home_decor",
  specialty_products: "specialty_gifts", specialty_finds: "specialty_gifts",
  specialty_goods: "specialty_gifts", specialty_items: "specialty_gifts",
  gourmet_products: "specialty_gifts", gourmet_treats: "specialty_gifts",
  gourmet_market: "specialty_gifts", boutique_items: "specialty_gifts",
  unique_products: "specialty_gifts", olive_oils: "specialty_gifts",
  balsamic_vinegars: "specialty_gifts", gift_sets: "gifts", gift_items: "gifts",
  unique_gifts: "gifts", creative_gifts: "gifts", locally_made_gifts: "gifts",
  playful_gifts: "gifts", quirky_gifts: "gifts", luxury_gifts: "gifts",
  girls_trip_shopping: "gift_shopping", boutique_shopping: "gift_shopping",
  gift_shopping: "gift_shopping", art_gifts: "gifts", locally_made: "gifts",
  souvenirs: "souvenirs", beach_souvenirs: "souvenirs", beach_essentials: "souvenirs",
  beach_supplies: "souvenirs", beach_goods: "souvenirs", beach_gear: "souvenirs",
  local_products: "souvenirs", local_treasures: "souvenirs", travel_recovery_ritual: "travel_services",
  shoes: "footwear", footwear: "footwear", shoe_shop: "footwear", stylish_shoes: "footwear",
  comfortable_footwear: "footwear", womens_comfort_shoes: "footwear",
  running_shoes: "footwear", sandals: "footwear", flip_flops: "footwear",
  birkenstock: "footwear", hoka: "footwear", gabor_shoes: "footwear", on_running: "footwear",
  apparel: "apparel", clothing: "apparel", womens_clothing: "apparel",
  womens_clothing_boutique: "apparel", womens_apparel: "apparel",
  designer_womens_clothing: "apparel", mens_clothing: "apparel", mens_apparel: "apparel",
  trendy_menswear: "apparel", trendy_clothing: "apparel", trendy_apparel: "apparel",
  trendy_outfits: "apparel", casual_wear: "apparel", casual_basics: "apparel",
  casual_clothing: "apparel", casual_styles: "apparel", casual_tees: "apparel",
  classic_shirts: "apparel", chic_clothing: "apparel", chic_dresses: "apparel",
  chic_tops: "apparel", coastal_dresses: "apparel", colorful_dresses: "apparel",
  cotton_sweaters: "apparel", designer_casualwear: "apparel", designer_clothing: "apparel",
  dresses: "apparel", dresses_for_events: "apparel", elegant_dresses: "apparel",
  elegant_outfits: "apparel", elevated_coastal_style: "apparel",
  everyday_outfits: "apparel", everyday_pieces: "apparel", fashionable_attire: "apparel",
  fashionable_dresses: "apparel", fashionable_pieces: "apparel",
  hand_sewn_clothing: "apparel", inclusive_fashion: "apparel", lightweight_dresses: "apparel",
  loungewear: "apparel", natural_fiber_clothing: "apparel", nautical_inspired_clothing: "apparel",
  outerwear: "apparel", stylish_outerwear: "apparel", polos: "apparel",
  quality_clothing: "apparel", quality_apparel: "apparel", seasonal_clothing: "apparel",
  seasonal_fashion_pieces: "apparel", shirts: "apparel", stylish_shirts: "apparel",
  sundresses: "apparel", sweatshirts: "apparel", rosemary_beach_sweatshirts: "apparel",
  watercolor_logo_wear: "apparel", t_shirts: "apparel", tops: "apparel",
  womens_tops: "apparel", trousers: "apparel", unique_clothing: "apparel",
  unique_clothing_finds: "apparel", unique_designs: "apparel", unique_fashion: "apparel",
  unique_styles: "apparel", vintage_clothing: "apparel", vintage: "apparel",
  wedding_attire: "apparel", boho_chic_womenswear: "apparel", plus_size_fashion: "apparel",
  affordable_fashion: "apparel", inclusive_sizes: "apparel", clothing_store: "apparel",
  clothing_and_accessories_boutique: "apparel", coastal_lifestyle_apparel: "apparel",
  coastal_apparel: "apparel", last_minute_clothing: "apparel",
  special_occasion_outfits: "apparel", special_occasion_pieces: "apparel",
  formal_options: "apparel", stylish_clothing: "apparel", limited_sizes: "apparel",
  belts: "accessories", bags: "accessories", handcrafted_bags: "accessories",
  handmade_bags: "accessories", stylish_bags: "accessories", cover_ups: "swimwear",
  bikinis: "swimwear", one_piece_swimsuits: "swimwear", swimsuits: "swimwear",
  designer_swimwear: "swimwear", swimwear_pop_up_shop: "swimwear",
  beach_apparel: "beachwear", beach_clothing: "beachwear", beach_separates: "beachwear",
  high_end_beachwear: "beachwear", surfwear: "beachwear", surf_gear: "beachwear",
  board_shorts: "beachwear", resort_wear: "beachwear", resort_wear_boutique: "beachwear",
  resort_retail: "beachwear", upscale_resortwear: "beachwear",
  matching_resort_sets: "beachwear", vacation_friendly_apparel: "beachwear",
  relaxed_vacation_wear: "beachwear", coastal_boutique: "beachwear",
  coastal_lifestyle_boutique: "beachwear", coastal_style: "beachwear",
  beach_lifestyle_boutique: "beachwear", beach_lifestyle_gear: "beachwear",
  activewear_and_lifestyle_boutique: "beachwear", athletic_wear: "beachwear",
  athletic_accessories: "sporting_goods", quality_jackets: "apparel",
  kids_clothing: "kids_apparel", childrens_clothing: "kids_apparel",
  casual_wear_for_children: "kids_apparel", apparel_for_kids: "kids_apparel",
  infant_apparel: "kids_apparel", baby_essentials: "kids_apparel",
  pre_teen_fashion: "kids_apparel", kids_fashion: "kids_apparel",
  childrens_boutique: "kids_apparel", childrens_clothing_boutique: "kids_apparel",
  kids_clothing_boutique: "kids_apparel", toy_apparel: "kids_apparel",
  custom_hat_boutique: "hats", hats: "hats", headbands: "accessories",
  fine_jewelry: "jewelry", fine_jewelry_boutique: "jewelry", jewelry_store: "jewelry",
  handcrafted_jewelry: "jewelry", handmade_jewelry: "jewelry", custom_jewelry: "jewelry",
  custom_jewelry_services: "jewelry", estate_jewelry: "jewelry",
  colorful_jewelry: "jewelry", unique_jewelry_pieces: "jewelry",
  engagement_rings: "jewelry", vintage_watches: "jewelry", necklaces: "jewelry",
  charm_necklaces: "jewelry", bracelets: "jewelry", welded_bracelets: "jewelry",
  earrings: "jewelry", birthstone_charms: "jewelry", charm_bar: "jewelry",
  permanent_jewelry: "jewelry", jewelry_repair: "jewelry", jewelry_dishes: "jewelry",
  julie_vos_jewelry: "jewelry", linny_co_flatback_stud_earrings: "jewelry",
  paperclip_bases: "jewelry", toys: "toys", stuffed_animals: "toys",
  plush_toys: "toys", small_toys: "toys", novelty_toys: "toys", puzzles: "toys",
  games: "toys", video_games: "toys", build_your_own_bear: "toys",
  labubus: "toys", sprunkees: "candy", beach_toys: "toys",
  books: "books", beach_reads: "books", fiction_titles: "books",
  nonfiction_titles: "books", childrens_books: "books", travel_books: "books",
  bookmarks: "books", journals: "books", books_from_local_authors: "books",
  independent_bookstore: "books", art: "art", paintings: "art",
  local_paintings: "art", original_paintings: "art", local_art: "art",
  local_artist_pieces: "art", local_artworks: "art", affordable_art: "art",
  fine_art: "art", fine_art_photography: "art", wearable_art: "art",
  art_glass: "art", art_prints: "art", prints: "art", sculptures: "art",
  high_end_sculptures: "art", ceramics: "art", ceramic_items: "art",
  pottery: "art", mixed_media: "art", curated_art_pieces: "art",
  custom_art_pieces: "art", small_art_items: "art", art_commissions: "art",
  emerging_artists: "art", local_photography: "photography",
  global_photography: "photography", photographs: "art",
  photography_studio: "photography", candles: "gifts", local_candles: "gifts",
  beauty_brands: "beauty_products", beauty_products: "beauty_products",
  cosmetics: "beauty_products", skincare_brands: "beauty_products",
  grooming_products: "beauty_products", natural_soaps: "beauty_products",
  soaps: "beauty_products", bath_products: "beauty_products", lotions: "beauty_products",
  oils: "beauty_products", custom_blended_perfumes: "beauty_products",
  apothecary: "beauty_products", clean_beauty_shop: "beauty_products",
  after_sun_care_products: "beauty_products", pet_accessories: "pet_accessories",
  dog_accessories: "pet_accessories", dog_bandanas: "pet_accessories",
  dog_beds: "pet_accessories", dog_toys: "pet_accessories", dog_treats: "pet_accessories",
  leashes: "pet_accessories", collars: "pet_accessories", harnesses: "pet_accessories",
  small_gift_items_for_pet_owners: "pet_accessories", pet_boutique: "pet_accessories",
  pet_accessory_shop: "pet_accessories", dog_outfitter: "pet_accessories",
  pet_care: "veterinary_care", florida_native_plants: "plants",
  indoor_plants: "plants", outdoor_plants: "plants", succulents: "plants",
  garden_accessories: "plants", trees: "plants", fishing_supplies: "sporting_goods",
  sporting_goods: "sporting_goods", outdoor_gear: "sporting_goods",
  outdoor_gear_store: "sporting_goods", outdoor_outfitter: "sporting_goods",
  bait: "sporting_goods", sports_cards: "collectibles", trading_cards: "collectibles",
  nba_cards: "collectibles", graded_cards: "collectibles",
  sports_collectibles: "collectibles", sports_card_shop: "collectibles",
  collectibles: "collectibles", vintage_models: "collectibles",
  eyewear: "accessories", non_prescription_eyewear: "accessories",
  prescription_eyewear: "accessories", sunglasses: "accessories",
  goodr_sunglasses: "accessories", krewe_sunglasses: "accessories",
  unique_accessories: "accessories", fashion_accessories: "accessories",
  coastal_themed_accessories: "accessories", accessories: "accessories",
  bike_accessories: "sporting_goods",

  // activities / rentals
  bike_rental: "bike_rentals", bike_rentals: "bike_rentals", bike_rental_shop: "bike_rentals",
  bike_rental_company: "bike_rentals", bike_rental_service: "bike_rentals",
  bike_shop: "bike_rentals", bike_sales: "bike_rentals", bike_repair: "bike_rentals",
  bike_repairs: "bike_rentals", bike_tours: "bike_rentals", cruisers: "bike_rentals",
  e_bikes: "bike_rentals", electric_bikes: "bike_rentals",
  electric_bike_rentals: "bike_rentals", electric_bike_rental: "bike_rentals",
  electric_assist_bikes: "bike_rentals", pedal_assist_bikes: "bike_rentals",
  tandem_bikes: "bike_rentals",
  bosch_motors: "bike_rentals", child_seats: "bike_rentals", helmets: "bike_rentals",
  bikes: "bike_rentals",
  kayak_rental: "water_sports_rentals", kayak_rentals: "water_sports_rentals",
  paddleboard_rental: "water_sports_rentals", paddleboard_rentals: "water_sports_rentals",
  paddleboards: "water_sports_rentals", paddle_board_rentals: "water_sports_rentals",
  surf_rentals: "water_sports_rentals", surf_lessons: "water_sports_rentals",
  surf_school: "water_sports_rentals", surfboards: "water_sports_rentals",
  skimboards: "water_sports_rentals", snorkeling_gear: "water_sports_rentals",
  boogie_boards: "water_sports_rentals", water_sport_equipment: "water_sports_rentals",
  water_sports: "water_sports_rentals", water_sports_rental_shop: "water_sports_rentals",
  watersports_activities: "water_sports_rentals", jet_ski_rentals: "water_sports_rentals",
  jet_ski_tours: "water_sports_rentals", dolphin_cruises: "water_sports_rentals",
  beach_bonfires: "activities", beach_rentals: "water_sports_rentals",
  beach_rental_service: "water_sports_rentals", beach_gear_rental: "water_sports_rentals",
  beach_town_transportation: "transportation", adventure_rentals_30a: "water_sports_rentals",
  vehicle_rentals: "mobility_rental", board_gear: "water_sports_rentals",
  arcade_games: "toys", claw_machines: "toys", gaming_tables: "toys",
  gaming_studio: "toys", mahjong: "toys", art_activity: "art",
  art_activity_workshop: "art", glass_shard_workshop: "art",
  "3d_movies": "entertainment_screenings", first_run_films: "entertainment_screenings",
  movie_theater: "entertainment_screenings", opera_screenings: "entertainment_screenings",
  jumbo_digital_screens: "entertainment_screenings", promotional_movie_posters: "entertainment_screenings",
  performances: "live_music", performing_arts: "live_music", live_theater: "live_music",
  theater: "live_music", sports_events: "entertainment_screenings",

  // health & beauty
  beauty: "salon_services", beauty_services: "salon_services", beauty_bar: "salon_services",
  beauty_salon: "salon_services", salon: "salon_services", salon_and_spa: "salon_services",
  haircuts: "salon_services", hair_care: "salon_services", haircare: "salon_services",
  hair_highlighting: "salon_services", blowouts: "salon_services",
  gloss_or_glaze: "salon_services", hair_salon: "salon_services",
  nail_salon: "nail_services", nail_art: "nail_services", nail_care: "nail_services",
  nail_design: "nail_services", nail_enhancements: "nail_services", nails: "nail_services",
  manicures: "nail_services", pedicures: "nail_services", acrylic_nails: "nail_services",
  gel_nails: "nail_services", gel_services: "nail_services", polish_change: "nail_services",
  non_toxic_polish: "nail_services", dazzle_dry_pedicure: "nail_services",
  russian_manicure: "nail_services", luxury_manicure: "nail_services",
  detailed_nail_care: "nail_services", waxing: "spa_services",
  facials: "spa_services", body_treatments: "spa_services", body_scrubs: "spa_services",
  massages: "massage", massage_therapy: "massage", aromatherapy_massage: "massage",
  ashiatsu_massage: "massage", deep_tissue_massage: "massage",
  relaxation_massage: "massage", prenatal_massage: "massage",
  couples_massages: "massage", honey_lavender_retreat_massage: "massage",
  rosemary_lavender_scalp_ritual: "massage",
  group_spa_packages: "spa_services", multi_hour_spa_packages: "spa_services",
  organic_spray_tans: "spa_services", infrared_sauna_sessions: "spa_services",
  hydrafacial_treatments: "spa_services", med_spa_services: "spa_services",
  spa_and_nails: "spa_services", spa_services: "spa_services", spa_day: "spa_services",
  relaxation: "spa_services", relaxation_sessions: "spa_services",
  skin_examinations: "skincare", skincare_services: "skincare", skincare: "skincare",
  acne_treatment: "dermatology", eczema_treatment: "dermatology",
  psoriasis_treatment: "dermatology", advanced_dermatological_treatments: "dermatology",
  cosmetic_procedures: "dermatology", dermatologist: "dermatology",
  botox: "dermatology", fillers: "dermatology", dermatology_clinic: "dermatology",
  routine_cleanings: "dental_care", cosmetic_dentistry: "dental_care",
  teeth_whitening: "dental_care", teeth_cleaning: "dental_care",
  same_day_crowns: "dental_care", emergency_dental_care: "dental_care",
  dental_implants: "dental_care", extractions: "dental_care", dentures: "dental_care",
  braces: "dental_care", invisalign: "dental_care", dental_exams: "dental_care",
  dental_emergency: "dental_care", dental_office: "dental_care",
  dental_practice: "dental_care", dental_clinic: "dental_care",
  orthodontics_office: "dental_care", orthodontist: "dental_care",
  chiropractic: "chiropractic_care", chiropractic_adjustments: "chiropractic_care",
  chiropractic_clinic: "chiropractic_care", chiropractic_services: "chiropractic_care",
  posture_correction: "chiropractic_care", back_pain_relief: "chiropractic_care",
  therapy: "counseling", mental_health: "counseling", mental_health_support: "counseling",
  mental_health_practice: "counseling", counseling_services: "counseling",
  self_improvement: "counseling", personal_growth: "counseling",
  advanced_technology: "medical_care", healthcare_visit: "medical_care",
  routine_check_ups: "medical_care", medical_services: "medical_care",
  medical_clinic: "medical_care", family_medicine: "medical_care",
  primary_care: "medical_care", urgent_care: "medical_care",
  emergency_care: "medical_care", emergency_interventions: "medical_care",
  emergency_procedures: "medical_care", first_mammogram: "medical_care",
  mammograms: "medical_care", routine_scan: "medical_care", dexascans: "medical_care",
  womens_health_diagnostics: "medical_care", womens_diagnostic_center: "medical_care",
  follow_up_calls: "medical_care", follow_up_services: "medical_care",
  same_day_appointments: "medical_care", healthcare: "healthcare",
  healthcare_provider: "healthcare", healthcare_services: "healthcare",
  health_services: "healthcare", health: "healthcare", health_boost: "healthcare",
  language_support: "healthcare", learning: "healthcare",
  hospice_care: "hospice_rehab_care", rehabilitation: "hospice_rehab_care",
  rehabilitation_center: "hospice_rehab_care", hospice_provider: "hospice_rehab_care",
  veterinary_clinic: "veterinary_care", fitness: "fitness_classes",
  fitness_studio: "fitness_classes", fitness_center: "fitness_classes",
  fitness_classes: "fitness_classes", gym: "fitness_classes", cardio: "fitness_classes",
  strength_training: "fitness_classes", endurance: "fitness_classes",
  flexibility: "fitness_classes", exercise: "fitness_classes",
  group_classes: "fitness_classes", group_workouts: "fitness_classes",
  personal_training: "fitness_classes", dynamic_workouts: "fitness_classes",
  form_focused_workouts: "fitness_classes", lean_body_workout: "fitness_classes",
  sculpt_classes: "fitness_classes", bachelorette_party_workouts: "fitness_classes",
  structured_classes: "fitness_classes", classes: "fitness_classes",
  class: "fitness_classes", pilates: "yoga", pilates_studio: "yoga",
  reformer_pilates_classes: "yoga", pure_barre_classic: "yoga", pure_empower: "yoga",
  pure_reform: "yoga", yoga_studio: "yoga", yoga_classes: "yoga",
  yoga_apparel: "yoga", yoga_apparel_store: "yoga", chic_yoga_apparel: "yoga",
  vinyasa_flow: "yoga", yin_yoga: "yoga", power_yoga: "yoga",
  meditation_classes: "yoga", wellness_consultations: "wellness",
  wellness_service: "wellness", supportive_instructors: "fitness_classes",

  // home trades / professional
  hvac_system_repair: "hvac_repair", hvac_system_maintenance: "hvac_repair",
  a_c_system_maintenance: "hvac_repair", air_conditioning_repair: "hvac_repair",
  air_conditioning: "hvac_repair", ac_installation: "hvac_repair",
  air_handler_installation: "hvac_repair", condenser_installation: "hvac_repair",
  heating: "hvac_repair", heating_repair: "hvac_repair", heating_services: "hvac_repair",
  heating_system_repair: "hvac_repair", routine_hvac_maintenance: "hvac_repair",
  routine_maintenance_checks: "hvac_repair", hvac_repair: "hvac_repair",
  hvac_repairs: "hvac_repair", hvac_company: "hvac_repair", hvac_services: "hvac_repair",
  hvac_and_plumbing_services: "hvac_repair", portable_ac_units: "hvac_repair",
  generators: "hvac_repair", ductwork_installation: "hvac_repair",
  gas_piping: "hvac_repair", system_overhauls: "hvac_repair",
  maintenance_plans: "hvac_repair", plumbing_services: "plumbing",
  plumbing_repairs: "plumbing", plumbing_contractor: "plumbing",
  remodel_plumbing: "plumbing", small_plumbing_repairs: "plumbing",
  drain_clogs: "plumbing", leak_repair: "plumbing", sewer_repair: "plumbing",
  water_heaters: "plumbing", water_filtration: "plumbing", plumbing_fixture_selection: "plumbing",
  electrical_service: "electrical", electrical_work: "electrical",
  small_electrical_work: "electrical", roofing: "roofing",
  pest_control_company: "pest_control", pest_control_service: "pest_control",
  residential_pest_control: "pest_control", commercial_pest_control: "pest_control",
  termite_treatments: "pest_control", ant_treatments: "pest_control",
  mosquito_reduction: "pest_control", mosquito_treatments: "pest_control",
  indoor_pest_control: "pest_control", outdoor_pest_control: "pest_control",
  builder_pest_services: "pest_control", pest_solutions: "pest_control",
  taexx_pest_control_system: "pest_control", customized_treatment_plans: "pest_control",
  landscape_maintenance: "landscaping", landscape_design: "landscaping",
  landscape_installation: "landscaping", commercial_landscaping: "landscaping",
  residential_landscaping: "landscaping", landscaping_company: "landscaping",
  landscaping_services: "landscaping", landscaping_supplier: "landscaping",
  garden_design: "landscaping", edging: "landscaping", trimming: "landscaping",
  seasonal_clean_ups: "landscaping", sod: "lawn_care", mowing: "lawn_care",
  lawn_care: "lawn_care", lawn_treatment: "lawn_care", supplies: "landscaping",
  cleaning: "cleaning_services", house_cleaning: "cleaning_services",
  cleaning_service: "cleaning_services", cleaning_services: "cleaning_services",
  comprehensive_cleaning: "cleaning_services", residential_cleaning: "cleaning_services",
  vacation_rental_cleaning: "cleaning_services", cleaning_coordination: "cleaning_services",
  home_maintenance: "handyman", personal_home_management: "handyman",
  home_repair: "handyman", general_home_repairs: "handyman", home_service: "handyman",
  home_service_company: "handyman", home_services: "handyman", handyman_service: "handyman",
  handyman_services: "handyman", repair: "handyman", repairs: "handyman",
  carpentry_work: "handyman", assembly_services: "handyman",
  appliance_installation: "handyman",
  home_alarm_installations: "security_systems", security_cameras: "security_systems",
  security_services: "security_systems", smart_home_integrations: "security_systems",
  home_improvement: "home_improvement", home_organization: "home_improvement",
  home_renovation: "home_improvement", renovation: "home_improvement",
  renovation_design: "home_improvement", interior_design: "home_improvement",
  interior_design_firm: "home_improvement", interior_design_showroom: "home_improvement",
  interior_painting: "painting", exterior_painting: "painting",
  painting_services: "painting", painting_contractor: "painting",
  cabinet_painting: "painting", deck_painting: "painting", stain_painting: "painting",
  drywall: "handyman", drywall_repair: "handyman", flooring: "flooring",
  flooring_company: "flooring", commercial_flooring: "flooring",
  epoxy_floors: "flooring", garage_epoxy_flooring: "flooring",
  polyaspartic_flooring: "flooring", garage_flooring_company: "flooring",
  countertops: "cabinetry", cabinet_design: "cabinetry", cabinet_installation: "cabinetry",
  cabinet_company: "cabinetry", custom_cabinets: "cabinetry", custom_cabinetry: "cabinetry",
  custom_cabinetry_service: "cabinetry", cabinetry_services: "cabinetry",
  quality_cabinetry: "cabinetry", kitchen_cabinets: "cabinetry", kitchen_design: "cabinetry",
  garage_cabinets: "cabinetry", bathroom_cabinetry: "cabinetry", bathroom_design: "cabinetry",
  closet_design: "cabinetry", closet_installation: "cabinetry", closet_systems: "cabinetry",
  custom_closets: "cabinetry", custom_storage_solutions: "cabinetry",
  storage_solutions: "cabinetry", garage_storage: "cabinetry", overhead_racks: "cabinetry",
  slatwall_systems: "cabinetry", furniture_selection: "cabinetry",
  lighting_selection: "cabinetry", color_schemes: "cabinetry", decor_packages: "cabinetry",
  design_consultation: "cabinetry", free_in_home_consultation: "cabinetry",
  blinds: "window_treatments", shades: "window_treatments",
  custom_blinds: "window_treatments", custom_window_treatments: "window_treatments",
  window_treatment_company: "window_treatments", window_company: "window_treatments",
  window_treatments: "window_treatments", door_treatments: "window_treatments",
  doors: "window_treatments", windows: "window_treatments",
  plantation_shutters: "window_treatments", shutters: "window_treatments",
  banded_shades: "window_treatments", solar_shades: "window_treatments",
  lutron_motorized_shades: "window_treatments", wallpaper: "window_treatments",
  pillows: "home_decor", custom_bedding: "home_decor",
  new_home: "real_estate", trades: "contractors", contractors: "contractors",
  general_contractor: "contractors", restoration_company: "restoration",
  emergency_restoration: "restoration", fire_restoration: "restoration",
  mold_remediation: "restoration", water_mitigation: "restoration",
  reconstruction: "restoration", home_inspection: "home_inspection",
  property_inspection: "home_inspection",

  // professional / financial
  financial_planning: "financial_planning", financial_advice: "financial_planning",
  personalized_financial_advice: "financial_planning", financial_management: "financial_planning",
  retirement_planning: "financial_planning", investment_management: "financial_planning",
  estate_planning: "legal_services", budgeting: "financial_planning",
  cash_flow_management: "financial_planning", forecasting: "financial_planning",
  outsourced_cfo_services: "accounting", bookkeeping: "bookkeeping",
  tax_preparation: "tax_prep", tax_savings: "tax_prep", accounting_services: "accounting",
  accounting_service: "accounting", accounting_firm: "accounting",
  financial_services: "financial_planning", financial_services_association: "financial_planning",
  financial_advisor: "financial_planning", payroll_solutions: "bookkeeping",
  payroll_services: "bookkeeping", merchant_services: "banking",
  payment_processing: "banking", banking: "banking", banking_services: "banking",
  bank: "banking", atm_services: "banking", business_accounts: "banking",
  personal_accounts: "banking", personal_banking: "banking", loans: "banking",
  mortgage_options: "real_estate", financial_assistance: "banking",
  auto_insurance: "insurance", home_insurance: "insurance", homeowners_insurance: "insurance",
  life_insurance: "insurance", personal_insurance: "insurance",
  personal_service_insurance: "insurance", personalized_insurance_solutions: "insurance",
  personalized_insurance_packages: "insurance", tailored_insurance_solutions: "insurance",
  business_insurance: "insurance", construction_project_insurance: "insurance",
  rental_property_insurance: "insurance", affordable_insurance: "insurance",
  insurance_agency: "insurance", insurance_services: "insurance",
  competitive_rates: "insurance", legal_service: "legal_services",
  law_firm: "legal_services", law_office: "legal_services",
  business_law: "legal_services", family_law: "legal_services",
  legal_advice: "legal_services", professional_legal_advice: "legal_services",
  consultations: "legal_services", client_centered: "legal_services",
  real_estate_agency: "real_estate",
  real_estate_office: "real_estate", real_estate_services: "real_estate",
  real_estate_listings: "real_estate", real_estate_transactions: "real_estate",
  real_estate_closing: "title_escrow", real_estate_closings: "title_escrow",
  property_buying: "real_estate", property_selling: "real_estate",
  property_sales: "real_estate", property_search: "real_estate",
  property_tours: "real_estate", property_management: "property_management",
  property_management_company: "property_management",
  property_transactions: "real_estate", home_buying: "real_estate",
  home_selling: "real_estate", homes_for_sale: "real_estate",
  home_search_app: "real_estate", investment_properties: "real_estate",
  investment_property: "real_estate", permanent_residences: "real_estate",
  vacation_homes: "real_estate", vacation_rentals: "property_management",
  vacation_rental_service: "property_management", vacation_club: "real_estate",
  vacation_club_membership: "real_estate", local_insight: "real_estate",
  expert_agents: "real_estate",
  guest_communication: "property_management", cutting_edge_tools: "real_estate",
  tech_savvy: "real_estate", cozy_cottages: "real_estate",
  beachfront_condos: "real_estate", beachfront_property: "real_estate",
  beachfront_homes: "real_estate", stress_free_closings: "title_escrow",
  closing_services: "title_escrow", closing_agents: "title_escrow",
  escrow_services: "title_escrow", professional_escrow_services: "title_escrow",
  title_services: "title_escrow", title_service: "title_escrow",
  title_and_escrow_services: "title_escrow", title_company: "title_escrow",
  title_insurance: "title_escrow", title_searches: "title_escrow",
  title_services_office: "title_escrow", office: "coworking",
  hourly_desk_rentals: "coworking", flexible_office_space: "coworking",
  coworking_space: "coworking", flexible_workspace: "coworking",
  meeting_rooms: "coworking", dual_monitors: "coworking", fast_wi_fi: "coworking",
  wi_fi: "coworking", wifi: "coworking", laptop_friendly: "coworking",
  remote_work: "coworking", tech_support: "coworking",
  reliable_wi_fi: "coworking", printing_facilities: "printing_shipping",
  shipping: "printing_shipping", shipping_services: "printing_shipping",
  shipping_service: "printing_shipping", shipping_and_printing_services: "printing_shipping",
  basic_shipping_services: "printing_shipping", printing: "printing_shipping",
  printing_services: "printing_shipping", last_minute_printing: "printing_shipping",
  postal_services: "printing_shipping", post_office: "printing_shipping",
  po_boxes: "printing_shipping", package_drop_offs: "printing_shipping",
  packaging_solutions: "printing_shipping", packing: "printing_shipping",
  bubble_wrap: "printing_shipping", boxes: "printing_shipping",
  portrait: "photography", chauffeur_service: "transportation",
  private_car_service: "transportation", corporate_transportation: "transportation",
  event_transportation: "transportation", wedding_transportation: "transportation",
  airport_shuttle: "transportation", towing: "transportation",
  travel_service: "travel_services", tourist_information_office: "travel_services",
  visitor_information: "travel_services", concierge_services: "travel_services",
  local_excursions: "travel_services", local_discounts: "travel_services",
  local_trails: "travel_services", scenic_trails: "travel_services",
  maps: "travel_services", accommodation: "travel_services", hotel: "travel_services",
  boutique_hotel: "travel_services", boutique_inn: "travel_services",
  inn: "travel_services", luxury_hotel: "travel_services", lodging: "travel_services",
  stay: "travel_services", luxury_accommodations: "travel_services",
  private_access: "travel_services", stunning_views: "travel_services",
  sunset_views: "travel_services", gulf_views: "travel_services",
  gulf_view: "travel_services", special_event_spaces: "travel_services",
  venue: "travel_services", event_venue: "travel_services",
  private_events: "travel_services", iconic: "travel_services",
  events: "travel_services",
};

/** Ordered keyword rules for anything not caught by the exact synonym map. First match wins. */
export const TAG_KEYWORD_RULES: Array<{ pattern: RegExp; tag: string }> = [
  { pattern: /shrimp|oyster|crab|lobster|snapper|scallop|seafood|ceviche/i, tag: "seafood" },
  { pattern: /steak|ribeye|filet|prime rib|tomahawk/i, tag: "steak" },
  { pattern: /sushi|sashimi|nigiri|tuna roll/i, tag: "sushi" },
  { pattern: /pizza|pizzeria/i, tag: "pizza" },
  { pattern: /\bbbq\b|barbecue|brisket/i, tag: "bbq" },
  { pattern: /burger/i, tag: "burgers" },
  { pattern: /\btaco|burrito|enchilada|fajita|salsa|mexican/i, tag: "mexican" },
  { pattern: /italian|pasta|alfredo|lasagna|piccata/i, tag: "italian" },
  { pattern: /sushi|asian|thai|japanese|noodle|pan-asian/i, tag: "asian" },
  { pattern: /gyro|mediterranean|greek/i, tag: "mediterranean" },
  { pattern: /sandwich|sub\b|wrap|grilled cheese|cheesesteak|cubano/i, tag: "sandwiches" },
  { pattern: /crepe/i, tag: "crepes" },
  { pattern: /dumpling|pork bun/i, tag: "dumplings" },
  { pattern: /wing/i, tag: "wings" },
  { pattern: /hot dog/i, tag: "hot_dogs" },
  { pattern: /pancake|waffle|biscuit|omelet|benedict|egg roll|croissant/i, tag: "pastries" },
  { pattern: /donut|doughnut/i, tag: "donuts" },
  { pattern: /candy|lollipop|gummy|gummies|praline|brittle/i, tag: "candy" },
  { pattern: /chocolate|fudge|cacao/i, tag: "chocolate" },
  { pattern: /ice cream|gelato|frozen yogurt|sherbet|shaved ice|snow cone/i, tag: "ice_cream" },
  { pattern: /acai|pitaya/i, tag: "acai_bowls" },
  { pattern: /coffee|latte|espresso|cortado|cold brew/i, tag: "coffee" },
  { pattern: /\btea\b/i, tag: "tea" },
  { pattern: /smoothie|milkshake|shake\b/i, tag: "smoothies" },
  { pattern: /wine\b/i, tag: "wine" },
  { pattern: /\bbeer\b|\bipa\b/i, tag: "beer" },
  { pattern: /cocktail|martini|mule|margarita|pina colada/i, tag: "cocktails" },
  { pattern: /jewelry|jewellery|earring|necklace|bracelet|ring\b/i, tag: "jewelry" },
  { pattern: /dress|apparel|clothing|shirt|top\b|sweater|outfit|romper|jumpsuit|fashion/i, tag: "apparel" },
  { pattern: /shoe|footwear|sandal|sneaker/i, tag: "footwear" },
  { pattern: /swim|bikini/i, tag: "swimwear" },
  { pattern: /surf|resort wear|beachwear|beach apparel/i, tag: "beachwear" },
  { pattern: /kids?[\s_-]|child(ren)?[\s_-]|infant|toddler/i, tag: "kids_apparel" },
  { pattern: /decor|furnishing|furniture|home\s?interior/i, tag: "home_decor" },
  { pattern: /\bgift\b/i, tag: "gifts" },
  { pattern: /gourmet|specialty (product|good|item)/i, tag: "specialty_gifts" },
  { pattern: /book(store|s)?\b/i, tag: "books" },
  { pattern: /art\b|painting|sculpture|ceramic|pottery|gallery/i, tag: "art" },
  { pattern: /toy|game\b|puzzle|arcade/i, tag: "toys" },
  { pattern: /card(s)?\b|collectible/i, tag: "collectibles" },
  { pattern: /skincare|cosmetic|beauty product|soap|lotion|perfume/i, tag: "beauty_products" },
  { pattern: /\bpet\b|\bdog\b/i, tag: "pet_accessories" },
  { pattern: /plant\b|succulent|garden/i, tag: "plants" },
  { pattern: /fishing|outdoor gear|camping/i, tag: "sporting_goods" },
  { pattern: /bike|bicycle|cruiser/i, tag: "bike_rentals" },
  { pattern: /kayak|paddleboard|surfboard|snorkel|jet ski|watersport|water sport|boogie board|skimboard|dolphin cruise/i, tag: "water_sports_rentals" },
  { pattern: /golf cart|lsv|mobility rental/i, tag: "mobility_rental" },
  { pattern: /hair|salon|blowout|haircut/i, tag: "salon_services" },
  { pattern: /nail\b|manicure|pedicure/i, tag: "nail_services" },
  { pattern: /spa\b|facial|sauna|hydrafacial/i, tag: "spa_services" },
  { pattern: /massage/i, tag: "massage" },
  { pattern: /dermatolog|botox|filler|acne|eczema|psoriasis/i, tag: "dermatology" },
  { pattern: /dental|dentist|teeth|orthodont|braces|invisalign/i, tag: "dental_care" },
  { pattern: /chiroprac/i, tag: "chiropractic_care" },
  { pattern: /counsel|therapy|mental health/i, tag: "counseling" },
  { pattern: /hospice|rehab/i, tag: "hospice_rehab_care" },
  { pattern: /veterinar|\bvet\b/i, tag: "veterinary_care" },
  { pattern: /fitness|gym\b|cardio|strength training|workout/i, tag: "fitness_classes" },
  { pattern: /yoga|pilates/i, tag: "yoga" },
  { pattern: /\bhvac\b|air condition|\bac\b|heating|ductwork|generator/i, tag: "hvac_repair" },
  { pattern: /plumb|drain|leak repair|water heater/i, tag: "plumbing" },
  { pattern: /electric(al)?/i, tag: "electrical" },
  { pattern: /\broof/i, tag: "roofing" },
  { pattern: /pest|termite|mosquito|exterminat/i, tag: "pest_control" },
  { pattern: /landscap|lawn|garden design|sod\b|mowing|edging|trimming/i, tag: "landscaping" },
  { pattern: /clean(ing)?/i, tag: "cleaning_services" },
  { pattern: /handyman|carpentry|assembly|general home repair/i, tag: "handyman" },
  { pattern: /security|alarm/i, tag: "security_systems" },
  { pattern: /renovat|interior design|home organi/i, tag: "home_improvement" },
  { pattern: /\bpaint/i, tag: "painting" },
  { pattern: /floor|epoxy/i, tag: "flooring" },
  { pattern: /cabinet|closet|countertop|kitchen design/i, tag: "cabinetry" },
  { pattern: /blind|shade|shutter|window treatment|wallpaper|\bdoor\b|\bwindow\b/i, tag: "window_treatments" },
  { pattern: /restoration|mold|water mitigation|fire damage/i, tag: "restoration" },
  { pattern: /inspection/i, tag: "home_inspection" },
  { pattern: /tax\b/i, tag: "tax_prep" },
  { pattern: /bookkeep|payroll/i, tag: "bookkeeping" },
  { pattern: /accounting|cfo/i, tag: "accounting" },
  { pattern: /financial|invest|retirement|budgeting|cash flow/i, tag: "financial_planning" },
  { pattern: /bank(ing)?|atm|merchant service|payment processing/i, tag: "banking" },
  { pattern: /insurance/i, tag: "insurance" },
  { pattern: /\blegal\b|attorney|law firm|law office/i, tag: "legal_services" },
  { pattern: /real estate|realtor|property (buying|selling|sales|search|tour)|home (buying|selling)|investment propert/i, tag: "real_estate" },
  { pattern: /title|escrow|closing/i, tag: "title_escrow" },
  { pattern: /property management|vacation rental/i, tag: "property_management" },
  { pattern: /photograph/i, tag: "photography" },
  { pattern: /coworking|desk rental|meeting room|flexible (office|workspace)/i, tag: "coworking" },
  { pattern: /shipping|printing|postal|po box|package/i, tag: "printing_shipping" },
  { pattern: /transport|shuttle|chauffeur|car service|towing/i, tag: "transportation" },
  { pattern: /hotel|inn\b|lodging|accommodation|concierge|resort/i, tag: "travel_services" },
];

/** Canonical business_type phrases (human-readable, lowercase — not slugs; nothing renders these). */
export const CANONICAL_BUSINESS_TYPES: string[] = [
  "restaurant", "seafood restaurant", "steakhouse", "casual restaurant",
  "fine dining restaurant", "breakfast restaurant", "pizza restaurant",
  "italian restaurant", "mexican restaurant", "asian restaurant",
  "mediterranean restaurant", "barbecue restaurant", "cafe", "sandwich shop",
  "acai bowl restaurant",
  "bar", "wine bar", "sports bar", "tiki bar", "cigar lounge", "juice bar",
  "coffee shop", "ice cream shop", "donut shop", "candy store", "dessert shop",
  "bakery",
  "clothing boutique", "kids clothing boutique", "gift shop",
  "home decor shop", "general store", "grocery store", "art gallery",
  "surf shop", "jewelry store", "footwear store", "bookstore", "bike shop",
  "specialty retail shop", "pet boutique",
  "hotel", "attraction", "theater", "arcade", "activity rental shop",
  "bike rental shop", "water sports rental shop",
  "fitness studio", "yoga studio", "hair salon", "nail salon", "spa",
  "medical clinic", "dental practice", "veterinary clinic",
  "real estate agency", "title & escrow company", "insurance agency",
  "bank", "financial advisor", "accounting firm", "law firm",
  "photography studio", "event venue",
  "hvac company", "plumbing company", "electrical contractor",
  "roofing contractor", "pest control company", "landscaping company",
  "cleaning company", "handyman service", "general contractor",
  "restoration company", "window treatment company", "cabinetry company",
  "flooring company", "painting contractor", "home inspection service",
  "security company", "property management company", "counseling practice",
  "hospice provider", "rehabilitation center", "dermatology clinic",
  "coworking space", "shipping & printing service", "transportation service",
  "travel service", "healthcare provider", "consulting firm",
  "interior design firm", "sushi restaurant",
];

export const CANONICAL_BUSINESS_TYPE_SET = new Set(CANONICAL_BUSINESS_TYPES);

/** Exact-match business_type synonym map (key = normalizeSlug(raw business_type)). */
export const BUSINESS_TYPE_SYNONYMS: Record<string, string> = {
  seafood_restaurant: "seafood restaurant", casual_restaurant: "casual restaurant",
  fine_dining_restaurant: "fine dining restaurant", breakfast_restaurant: "breakfast restaurant",
  pizza_restaurant: "pizza restaurant", pizzeria: "pizza restaurant",
  italian_restaurant: "italian restaurant", mexican_restaurant: "mexican restaurant",
  upscale_asian_restaurant: "asian restaurant", barbecue_restaurant: "barbecue restaurant",
  casual_dining_restaurant: "casual restaurant", casual_beach_restaurant: "casual restaurant",
  casual_seafood_spot: "seafood restaurant", coastal_oyster_bar_and_restaurant: "seafood restaurant",
  southern_coastal_restaurant: "casual restaurant", healthy_food_restaurant: "casual restaurant",
  smoothie_bowl_restaurant: "acai bowl restaurant", crepe_restaurant: "cafe",
  crepery: "cafe", cafe: "cafe", casual_cafe: "cafe", grilled_cheese_restaurant: "sandwich shop",
  hot_dog_restaurant: "sandwich shop", sub_sandwich_shop: "sandwich shop",
  burger_restaurant: "casual restaurant", greek_restaurant: "mediterranean restaurant",
  taqueria: "mexican restaurant", beach_bar_and_grill: "bar",
  bar_in_grayton_beach: "bar", casual_dining_bar: "bar", frozen_drink_bar: "bar",
  irish_pub: "bar", sports_bar: "sports bar", sports_tavern: "sports bar",
  wine_bar: "wine bar", juice_bar: "juice bar", cigar_lounge: "cigar lounge",
  tiki_bar_and_restaurant: "tiki bar", coffee_shop: "coffee shop",
  ice_cream_shop: "ice cream shop", dessert_shop: "dessert shop",
  candy_store: "candy store", candy_and_gift_shop: "candy store",
  cookies_and_sweets_shop: "bakery", donut_shop: "donut shop",
  acai_bowl_restaurant: "acai bowl restaurant",

  womens_clothing_boutique: "clothing boutique",
  shopping_boutique: "clothing boutique", boutique: "clothing boutique",
  clothing_boutique: "clothing boutique", clothing_store: "clothing boutique",
  clothing_and_accessories_boutique: "clothing boutique", coastal_boutique: "clothing boutique",
  coastal_lifestyle_boutique: "clothing boutique", beach_lifestyle_boutique: "clothing boutique",
  activewear_and_lifestyle_boutique: "clothing boutique", local_apparel_shop: "clothing boutique",
  lifestyle_retail_shop: "clothing boutique", mens_clothing_boutique: "clothing boutique",
  mens_clothing_store: "clothing boutique", menswear_boutique: "clothing boutique",
  resort_wear_boutique: "clothing boutique", swimwear_pop_up_shop: "clothing boutique",
  handcrafted_bag_boutique: "clothing boutique", custom_hat_boutique: "clothing boutique",
  yoga_apparel_store: "clothing boutique", upscale_shopping: "clothing boutique",
  unique_shopping_experience: "clothing boutique", shopping_store: "clothing boutique",
  shopping: "clothing boutique", retail_store: "specialty retail shop",
  childrens_clothing_boutique: "kids clothing boutique", childrens_boutique: "kids clothing boutique",
  kids_clothing_boutique: "kids clothing boutique",
  gift_shop: "gift shop", home_decor_boutique: "home decor shop",
  home_furnishings_showroom: "home decor shop", home_interiors_shop: "home decor shop",
  interior_design_showroom: "home decor shop", furniture_store: "home decor shop",
  general_store: "general store", grocery_store: "grocery store",
  butcher_shop: "grocery store", gourmet_market: "grocery store",
  gourmet_olive_oil_store: "grocery store", art_gallery: "art gallery",
  art_and_design_studio: "art gallery", art_collective: "art gallery",
  art_shop: "art gallery", art_studio: "art gallery", fine_art_photography_gallery: "art gallery",
  surf_shop: "surf shop", jewelry_store: "jewelry store",
  fine_jewelry_boutique: "jewelry store", footwear_store: "footwear store",
  shoe_shop: "footwear store", independent_bookstore: "bookstore",
  independent_record_store: "specialty retail shop", bike_shop: "bike shop",
  bike_rental_shop: "bike rental shop", bike_rental_company: "bike rental shop",
  bike_rental_service: "bike rental shop", electric_bike_rental: "bike rental shop",
  water_sports_rental_shop: "water sports rental shop", specialty_retail: "specialty retail shop",
  sports_card_shop: "specialty retail shop", pet_accessory_shop: "pet boutique",
  pet_boutique: "pet boutique", dog_outfitter: "pet boutique",
  outdoor_gear_store: "specialty retail shop", outdoor_outfitter: "specialty retail shop",
  fragrance_shop: "specialty retail shop", clean_beauty_shop: "specialty retail shop",
  optical_shop: "specialty retail shop", artisan_crafts_boutique: "specialty retail shop",
  vacation_club: "specialty retail shop", market: "general store",
  wine_and_bottle_shop: "specialty retail shop", mobility_rental: "bike rental shop",

  hotel: "hotel", boutique_hotel: "hotel", luxury_hotel: "hotel", inn: "hotel",
  movie_theater: "theater", theater: "theater", arcade: "arcade",
  gaming_studio: "arcade", activity: "attraction", activity_rental: "activity rental shop",
  art_activity_workshop: "art gallery",
  activity_rental_shop: "activity rental shop", activity_services: "activity rental shop",
  beach_rental_service: "activity rental shop", surf_school: "activity rental shop",
  electric_bike_rental_2: "bike rental shop",

  fitness_studio: "fitness studio", fitness_center: "fitness studio",
  yoga_studio: "yoga studio", pilates_studio: "yoga studio",
  hair_salon: "hair salon", salon: "hair salon", beauty_salon: "hair salon",
  beauty_bar: "hair salon", nail_salon: "nail salon", spa: "spa",
  spa_and_nails: "spa", spa_services: "spa", salon_and_spa: "spa",
  medical_clinic: "medical clinic", healthcare: "medical clinic",
  medical_services: "medical clinic", dental_office: "dental practice",
  dental_practice: "dental practice", orthodontics_office: "dental practice",
  veterinary_clinic: "veterinary clinic", womens_diagnostic_center: "medical clinic",
  chiropractic_clinic: "medical clinic", chiropractic_services: "medical clinic",
  sushi_bar: "sushi restaurant", wellness_service: "medical clinic",
  dental_clinic: "dental practice", orthodontist: "dental practice",
  healthcare_provider: "healthcare provider",

  real_estate_agency: "real estate agency", real_estate_office: "real estate agency",
  real_estate_services: "real estate agency", service_listing: "real estate agency",
  property_management_company: "real estate agency",
  consulting_service: "consulting firm", owners_association_service: "property management company",
  title_service: "title & escrow company", title_services: "title & escrow company",
  title_services_office: "title & escrow company", title_and_escrow_services: "title & escrow company",
  title_company: "title & escrow company", insurance_agency: "insurance agency",
  insurance_services: "insurance agency", bank: "bank", banking: "bank",
  banking_services: "bank", financial_services: "financial advisor",
  financial_services_association: "financial advisor", financial_advisor: "financial advisor",
  accounting_services: "accounting firm", accounting_service: "accounting firm",
  payroll_services: "accounting firm",
  accounting_firm: "accounting firm", law_firm: "law firm", legal_service: "law firm",
  legal_services: "law firm", photography_studio: "photography studio",
  event_venue: "event venue",

  hvac_company: "hvac company", hvac_services: "hvac company",
  hvac_and_plumbing_services: "hvac company", plumbing_services: "plumbing company",
  plumbing_contractor: "plumbing company", electrical_service: "electrical contractor",
  roofing: "roofing contractor", pest_control_company: "pest control company",
  pest_control_service: "pest control company", landscaping_company: "landscaping company",
  landscaping_services: "landscaping company", landscaping_supplier: "landscaping company",
  cleaning_service: "cleaning company", cleaning_services: "cleaning company",
  handyman_service: "handyman service", handyman_services: "handyman service",
  home_service_company: "handyman service", home_maintenance: "handyman service",
  general_contractor: "general contractor", contractors: "general contractor",
  restoration_company: "restoration company", window_treatment_company: "window treatment company",
  window_company: "window treatment company", custom_window_treatments: "window treatment company",
  cabinet_company: "cabinetry company", cabinetry_services: "cabinetry company",
  custom_cabinetry_service: "cabinetry company", custom_storage_solutions: "cabinetry company",
  flooring_company: "flooring company", garage_flooring_company: "flooring company",
  painting_contractor: "painting contractor", security_services: "security company",
  property_management: "property management company",
  vacation_rental_service: "property management company",
  counseling_services: "counseling practice", mental_health_practice: "counseling practice",
  hospice_provider: "hospice provider", rehabilitation_center: "rehabilitation center",
  dermatology_clinic: "dermatology clinic",
  coworking_space: "coworking space", flexible_workspace: "coworking space",
  shipping_service: "shipping & printing service", shipping_and_printing_services: "shipping & printing service",
  postal_services: "shipping & printing service", post_office: "shipping & printing service",
  tourist_information_office: "travel service",
  travel_service: "travel service", private_car_service: "transportation service",
  rental_service: "transportation service", beach_bonfire_service: "activity rental shop",
  watersports_activities: "water sports rental shop", paddleboard_tour: "water sports rental shop",
  service: "specialty retail shop", services: "specialty retail shop",
};
