-- Curated homepage / editorial spotlights: businesses, categories, towns.
-- Required by /admin/featured, app/page (featured blocks), and updateBusinessAction when "Feature on homepage" is set.

CREATE TABLE IF NOT EXISTS public.featured_content (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text NOT NULL,
  reference_id text NOT NULL,
  title text NOT NULL,
  description text,
  badge text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_featured_content_type_sort
  ON public.featured_content (content_type, sort_order);

CREATE INDEX IF NOT EXISTS idx_featured_content_lookup
  ON public.featured_content (content_type, reference_id);

-- At most one featured row per (type, entity) — matches admin insert/update logic.
CREATE UNIQUE INDEX IF NOT EXISTS uq_featured_content_type_ref
  ON public.featured_content (content_type, reference_id);

CREATE OR REPLACE FUNCTION public.set_featured_content_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS featured_content_set_updated_at ON public.featured_content;
CREATE TRIGGER featured_content_set_updated_at
  BEFORE UPDATE ON public.featured_content
  FOR EACH ROW
  EXECUTE PROCEDURE public.set_featured_content_updated_at();

COMMENT ON TABLE public.featured_content IS 'Admin-curated featured items for home and promos; reference_id matches businesses.id, categories.id, or towns.id as text.';
